

SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOME_ESCOLA,
ETAPA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,
CONCAT (TP_LOGRADOURO,' ',ENDEREÇO,', ',NR,'- ',COMPL,', ',BAIRRO) AS ENDEREÇO,
CRDATE
INTO ##ALUYNOS019405
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS WHERE CD_ESCOLA=019405