
/*
Solicitamos relatório EOL dos alunos de 5º ano das EMEFs Plinio Marcos e Pedro Geraldo Schunck com os dados abaixo, para atendimento a continuidade 2024:

Nome
RA
Endereço
*/

DROP TABLE ##ALUNOS_QUINTO_ANO_EMEFS_019496_019104
SELECT 
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
B.SG_ETAPA,
B.SG_SERIE_ENSINO,
B.CD_ALUNO,
B.NM_ALUNO,
concat(A.TP_LOGRADOURO,' ',A.ENDEREÇO,', ',A.NR,' ',A.COMPL,' ',A.BAIRRO) AS END_ALUNO,
A.CRDATE
INTO ##ALUNOS_QUINTO_ANO_EMEFS_019496_019104
FROM VW_ALUNOS_ENDERECOS A
JOIN SME_ALUNOS_DIARIO B ON A.COD_ALUNO=B.CD_ALUNO
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA
WHERE A.cd_escola IN (019496,019194) AND B.SG_SERIE_ENSINO = '5º ANO'
--SELECT * FROM ##ALUNOS_QUINTO_ANO_EMEFS_019496_019104


