

--CONSULTA QUE CALCULA A DISTÂNCIA DOS ENDEREÇOS DOS ALUNOS DE UMA DETERMINADA ESCOLA PARA UM NOVO ENDEREÇO

 --nome da criança, codigo eol da criança, endereço, nome do CEI em 2022, agrupamento em 2022, distancia


USE Db_Local_0


/*DROP TABLE ##END_DESTINO
CREATE TABLE ##END_DESTINO (
	ID  INT IDENTITY(0,1),
	ENDERECO NVARCHAR(200) NULL,
	LAT FLOAT NULL,
	LON FLOAT NULL,
	DATA_GERACAO DATETIME NULL	)*/
TRUNCATE TABLE ##END_DESTINO

--ENDEREÇO 1
DECLARE @END NVARCHAR(200) SET @END ='Av. Lins de Vasconcelos, 1191 - Cambuci'--FORNECER O ENDEREÇO
DECLARE @LAT_Y FLOAT SET @LAT_Y = -23.573724249181208  	--INFORMAR A LATITUDE DO ENDEREÇO(GOOGLE  MAPS)
DECLARE	@LON_X FLOAT SET @LON_X = -46.62282095792112    --INFORMAR A LONGITUDE DO ENDEREÇO(GOOGLE  MAPS)
INSERT INTO ##END_DESTINO  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO
/*
--ENDEREÇO 2
DECLARE @END NVARCHAR(200) SET @END ='Rua Jose Diogo Abadiano, cep 04855-440, setor 3006, DRE Capela do Socorro'--FORNECER O ENDEREÇO
DECLARE @LAT_Y FLOAT SET @LAT_Y =  -23.773406004848177 	--INFORMAR A LATITUDE DO ENDEREÇO(GOOGLE  MAPS)
DECLARE	@LON_X FLOAT SET @LON_X =  -46.68321081542278   --INFORMAR A LONGITUDE DO ENDEREÇO(GOOGLE  MAPS)
INSERT INTO ##END_DESTINO  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO
*/
--------------------------------------------------------------------------------
--SELECT * FROM ##END_DESTINO
--SELECT TOP 1 * FROM TBL_ENDERECOS_ALUNOS

DROP TABLE ##ALUNOS_NOVO_DESTINO
SELECT
A.ID,
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOME_ESCOLA,
ETAPA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,
MÃE_ALUNO,
RESPONSÁVEL,
DDD,
TEL_CELULAR,
TEL_FIXO,
TP_LOGRADOURO,
B.ENDEREÇO,
NR,
COMPL,
BAIRRO,

FLOOR(DIST_ALU_ESCOLA) AS DIST_ESCOLA,
A.ENDERECO AS END_DESTINO,
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO*1000000 - (LAT * 1000000) ),2) +  POWER((LON_ALUNO*1000000  - (LON * 1000000)),2)) / 10)/0.6) AS distancia
--B.CRDATE

INTO ##ALUNOS_NOVO_DESTINO

FROM ##END_DESTINO A, TBL_ENDERECOS_ALUNOS B

WHERE-- ETAPA = 'ED INF'
B.CD_ESCOLA = '309037' -- INFORMAR O CD_ESCOLA DA UNIDADE DE MATRICULA DOS ALUNOS
AND 
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO*1000000 - (LAT * 1000000) ),2) +  POWER((LON_ALUNO*1000000  - (LON * 1000000)),2)) / 10)/0.6)<=1500


SELECT * FROM ##ALUNOS_NOVO_DESTINO

SELECT 
ID,
END_DESTINO,
NOME_ALUNO  AS [nome da criança], 
COD_ALUNO  AS [codigo eol da criança], 
TP_logradouro,
ENDEREçO,
NR,
COMPL,
BAIRRO, 
NOME_ESCOLA AS [nome do CEI em 2022], 
SERIE_ANO AS [agrupamento em 2022],
distancia
INTO ##ID1
from ##ALUNOS_NOVO_DESTINO WHERE ID=1

SELECT 
ID,
END_DESTINO,
NOME_ALUNO  AS [nome da criança], 
COD_ALUNO  AS [codigo eol da criança], 
TP_logradouro,
ENDEREçO,
NR,
COMPL,
BAIRRO, 
NOME_ESCOLA AS [nome do CEI em 2022], 
SERIE_ANO AS [agrupamento em 2022],
distancia
INTO ##ID0
from ##ALUNOS_NOVO_DESTINO WHERE ID=0


