

--LISTA DE ALUNOS RESIDENTES NO BAIRRO CHÁCARA MARIA TRINDADE - DRE PJ
select  * 
INTO ##ALUNOS_CH_MARIA_TRIDADE
from  TBL_ENDERECOS_ALUNOS_2023 WHERE BAIRRO IN ('CHACARA MARIA TRINDADE', 'CHÁCARA MARIA TRINDADE','CH MARIA TRINDADE') AND DRE = 'DRE - PJ'

