
DROP TABLE ##DISTRITOS_SUPREFEITURAS_DRES
SELECT 
A.CDIST,
A.DISTRITO,
C.CODLOC AS COD_DRE,
A.DIRET_MUN AS DRE,
B.cd_sub_prefeitura AS COD_SUB,
A.[PREFEITURA REGIONAL] AS SUBPREFEITURA,
DIRET_EST AS [DIRET ESTADO],
ZONA

INTO ##DISTRITOS_SUPREFEITURAS_DRES

FROM DREMDIST A
LEFT JOIN D_SUB_PREFEITURA B ON A.SIGLASUB=B.SG_SUB_PREFEITURA COLLATE Latin1_General_CI_AS
JOIN TBL_DRE C ON A.SIGLADRE= SUBSTRING(C.DRE,7,2)

--SELECT * FROM ##DISTRITOS_SUPREFEITURAS_DRES

