


SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOME_ESCOLA,
ETAPA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,
CONCAT(TP_LOGRADOURO,' ',ENDEREÇO,', ',NR,' ',COMPL,' ',BAIRRO) AS ENDERECO,
LAT_ALUNO,
LON_ALUNO
INTO ##ALUNOS_5_ANO_019196
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS WHERE CD_ESCOLA=019196 AND SERIE_ANO = '5º ANO'

SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CD_COORDENADA_GEO_Y AS LAT_ESC,
CD_COORDENADA_GEO_X AS LON_ESC
INTO ##EMEFS
FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%'

DROP TABLE ##EMEFS_PROXIMAS
SELECT 
A.*,CONCAT(B.SG_TP_ESCOLA,NOMESC) AS EMEF_PROXINA, 
FLOOR(FLOOR(SQRT(POWER(((LAT_ALUNO*1000000) - (LAT_ESC * 1000000) ),2) +  POWER(((LON_ALUNO*1000000)  - (LON_ESC * 1000000)),2)) / 10)/0.6) AS DISTÂNCIA
INTO ##EMEFS_PROXIMAS
FROM ##ALUNOS_5_ANO_019196 A, ##EMEFS B
WHERE FLOOR(FLOOR(SQRT(POWER(((LAT_ALUNO*1000000) - (LAT_ESC * 1000000) ),2) +  POWER(((LON_ALUNO*1000000)  - (LON_ESC * 1000000)),2)) / 10)/0.6) <=2000
ORDER BY COD_ALUNO
--SELECT * FROM ##EMEFS_PROXIMAS