

SELECT DISTINCT
A.AN_LETIVO,
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.CD_TURMA_ESCOLA,

COUNT (DISTINCT CASE WHEN DEF1 IS NOT NULL THEN A.CD_ALUNO ELSE NULL END) AS MT_NEE
INTO ##094978_2023



FROM SME_ALUNOS_DIARIO A
JOIN SME_CLASSES_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA

WHERE A.CD_ESCOLA='094978' AND A.SG_ETAPA IS NOT NULL AND DEF1 IS NOT NULL
GROUP BY
A.AN_LETIVO,
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.CD_TURMA_ESCOLA



SELECT DISTINCT
A.AN_LETIVO,
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.CD_TURMA_ESCOLA,

COUNT (DISTINCT CASE WHEN DEF1 IS NOT NULL THEN A.CD_ALUNO ELSE NULL END) AS MT_NEE



INTO ##094978_2022
FROM Db_Nov_22..SME_ALUNOS A
JOIN Db_Nov_22..SME_CLASSES B ON A.CD_TURMA_ESCOLA=B.CD_TURMA_ESCOLA
JOIN Db_Nov_22..SME_ESCOLA C ON A.CD_ESCOLA=C.CD_ESCOLA

WHERE A.CD_ESCOLA='094978' AND A.SG_ETAPA IS NOT NULL AND DEF1 IS NOT NULL
GROUP BY
A.AN_LETIVO,
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.CD_TURMA_ESCOLA

--SELECT TOP 10 * FROM SME_CLASSES_DIARIO

