

DROP TABLE ##ENDERECOS_ALUNOS_019522
select 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOME_ESCOLA,
ETAPA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,
MÃE_ALUNO,
RESPONSÁVEL,
TEL_CELULAR,
EMAIL_RESPONSAVEL,
CONCAT (TP_LOGRADOURO,' ',ENDEREÇO, ',',NR,'',COMPL,'',BAIRRO) AS ENDEREÇO
INTO ##ENDERECOS_ALUNOS_019522
from VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS
where cd_escola = 019252
--SELECT * FROM ##ENDERECOS_ALUNOS_019522