


DROP TABLE ##ENDEREÇOS_ALUNOS_UNIDADE_307899
SELECT 
DRE, 
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC, 
SG_ETAPA,
SG_SERIE_ENSINO,
COD_ALUNO,
NM_ALUNO,
TP_LOGRADOURO,
ENDEREÇO,
C.NR,
C.COMPL,
C.BAIRRO, 
CONVERT(VARCHAR,A.CRDATE-1, 103) AS DT_BASE 
INTO ##ENDEREÇOS_ALUNOS_UNIDADE_307899
FROM 


SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN VW_ALUNOS_ENDERECOS C ON A.CD_ALUNO=C.COD_ALUNO

WHERE A.CD_ESCOLA= 307899

--SELECT * FROM ##ENDEREÇOS_ALUNOS_UNIDADE_307899