
--CONSULTA - DATA E ANO DE CRIAÇÃO DAS ESCOLAS NO EOL - REDE DIRETA
DROP TABLE ##ESCOLAS_ANO_CRIACAO
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CONVERT(VARCHAR,DT_CRIACAO,103) AS DT_CRIACAO,
YEAR(DT_CRIACAO) AS AN_CRIACAO,
SITUACAO
INTO ##ESCOLAS_ANO_CRIACAO

FROM SME_ESCOLAS_ATOS_CRIACAO

--SELECT * FROM ##ESCOLAS_ANO_CRIACAO

SELECT top 12 * from MATRICULA