


DROP TABLE ##BASE_EMEF
SELECT 
--(ROW_NUMBER() OVER(ORDER BY CD_ESCOLA DESC)) AS ID1,
--(ROW_NUMBER() OVER(ORDER BY CD_ESCOLA)) AS ID2,

DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CD_COORDENADA_GEO_Y,
CD_COORDENADA_GEO_X
--INTO ##BASE_EMEF
FROM SME_ESCOLA_DIARIO
WHERE TP_ESCOLA IN (1,3,16) AND CD_SIT=1

--SELECT * FROM ##BASE_EMEF

DROP TABLE ##BASE_EMEF_DISTANCIA
SELECT DISTINCT
                     A.DRE AS DRE_A,A.CD_ESCOLA AS EOL_A,A.SG_TP_ESCOLA AS TIPO_A,A.NOMESC AS ESCOLA_A, 
       
	                 B.DRE AS DRE_B, B.CD_ESCOLA AS EOL_B , B.SG_TP_ESCOLA AS TIPO_B,B.NOMESC AS ESCOLA_B,

FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X * 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6) AS DISTANCIA,

CASE WHEN FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X * 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6) <= 250 THEN 'Até 250 m'
     WHEN FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X * 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6) BETWEEN 251 AND 500 THEN '251 a 500 m'
	 WHEN FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X * 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6) BETWEEN 501 AND 750 THEN '501 a 750 m'
	 WHEN FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X * 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6) BETWEEN 751 AND 1000 THEN '751 a 1000 m'
ELSE NULL END AS FAIXA
INTO ##BASE_EMEF_DISTANCIA
FROM ##BASE_EMEF A, ##BASE_EMEF B 

WHERE 

FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X* 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6)<=1000
AND 
FLOOR(FLOOR(SQRT(POWER((A.CD_COORDENADA_GEO_Y * 1000000 - (B.CD_COORDENADA_GEO_Y * 1000000) ),2) +  
		   POWER((A.CD_COORDENADA_GEO_X* 1000000 - (B.CD_COORDENADA_GEO_X * 1000000)),2))/10)/0.6)<>0



select 
            distinct case when EOL_A<EOL_B THEN EOL_A ELSE EOL_B END AS T1,
            case when EOL_A>EOL_B THEN EOL_A ELSE EOL_B END AS T2
--INTO ##BASE2			
FROM ##BASE_EMEF_DISTANCIA

ALTER TABLE ##BASE2 ADD CON2 VARCHAR(12) 
UPDATE ##BASE2 SET CON2 =CONCAT(T1,T2)

SELECT * FROM ##BASE2

SELECT DRE_A,EOL_A,TIPO_A,ESCOLA_A,DRE_B,EOL_B,TIPO_B,ESCOLA_B,DISTANCIA,FAIXA into ##BASE_EMEF_DISTANCIA1 FROM ##BASE_EMEF_DISTANCIA A
INNER JOIN ##BASE2 B ON A.CON1 = B.CON2
WHERE EOL_A IN (099350,019431) OR EOL_B IN (099350,019431)



--SELECT CD_ESCOLA FROM SME_ESCOLA WHERE NOMESC LIKE '%MILLOR%'
SELECT * FROM ##BASE_EMEF_DISTANCIA
SELECT * FROM ##BASE2


		   

SELECT EOL_A,EOL_B, ESCOLA_A,ESCOLA_B, DISTANCIA, CONCAT(EOL_A,EOL_B) AS CON1 FROM ##BASE_EMEF_DISTANCIA A
INNER JOIN (select 
            distinct case when EOL_A<EOL_B THEN EOL_A ELSE EOL_B END AS T1,
            case when EOL_A>EOL_B THEN EOL_A ELSE EOL_B END AS T2
			
FROM ##BASE_EMEF_DISTANCIA) B ON 


ALTER table ##BASE_EMEF_DISTANCIA add CON1 VARCHAR(12)
UPDATE ##BASE_EMEF_DISTANCIA SET CON1 =CONCAT(EOL_A,EOL_B)





