
DROP TABLE ##SETOR_5507
SELECT DISTINCT
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
B.CD_DIST,
B.SETOR,
B.ENDERECO,
B.NR,
B.BAIRRO,
B.CEP,
COUNT (CD_TURMA_ESCOLA) AS QT_TUR,
SUM(QT_VAGA_OFERECIDA) AS QT_VG,
SUM(AL_AT) AS QT_MT,
CONVERT( VARCHAR, B.CRDATE-1, 103) AS DT_BASE
INTO ##SETOR_5507
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE B.CD_DIST='55' AND SETOR ='07'  AND SG_ETAPA IS NOT NULL
GROUP BY
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
B.CD_DIST,
B.SETOR,
B.ENDERECO,
B.NR,
B.BAIRRO,
B.CEP,
B.CRDATE
--SELECT * FROM ##SETOR_5507
-------------------------------------------------------------------------------
DROP TABLE ##SETOR_5507_1
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CD_DIST,
SETOR,
ENDERECO,
NR,
BAIRRO,
CEP,
QT_TUR,
QT_VG,
QT_MT,
(QT_VG-QT_MT) AS VG_REM ,
DT_BASE
INTO ##SETOR_5507_1
FROM ##SETOR_5507
--SELECT * FROM ##SETOR_5507_1