

--SELECT * FROM SME_ESCOLA_DIARIO WHERE ENDERECO LIKE '%marche%'

DROP TABLE ##CL_MT_MEDI
SELECT 
DRE,
SG_TP_ESCOLA,
CD_ESCOLA,
NOMESC,
CL_M1,
MT_M1,
CL_M2,
MT_M2,
CL_M3,
MT_M3,
CL_M4,
MT_M4,
CL_MEDI,
MT_MEDI
INTO ##CL_MT_MEDI
FROM D_MISME_ESCOLA_TOTAL WHERE MT_MEDI <>0
UNION
SELECT 
DRE,
SG_TP_ESCOLA,
CD_ESCOLA,
NOMESC,
CL_M1,
MT_M1,
CL_M2,
MT_M2,
CL_M3,
MT_M3,
CL_M4,
MT_M4,
CL_MEDI,
MT_MEDI
FROM D_MISME_EE_ESCOLA_TOTAL WHERE MT_MEDI <>0
--SELECT * FROM ##CL_MT_MEDI
--------------------------------------------------------------------------------------------------------------------------
--RECORTE - IDADE
DROP TABLE ##MT_MEDIO_IDADE
SELECT B.DRE,B.SG_TP_ESCOLA, B.CD_ESCOLA,B.NOMESC,--,A.SG_ETAPA,A.SG_SERIE_ENSINO,

COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 14 THEN A.CD_ALUNO ELSE NULL END) AS '14 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 15 THEN A.CD_ALUNO ELSE NULL END) AS '15 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 16 THEN A.CD_ALUNO ELSE NULL END) AS '16 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 17 THEN A.CD_ALUNO ELSE NULL END) AS '17 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 18 THEN A.CD_ALUNO ELSE NULL END) AS '18 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 19 THEN A.CD_ALUNO ELSE NULL END) AS '19 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) = 20 THEN A.CD_ALUNO ELSE NULL END) AS '20 ANOS',
COUNT(DISTINCT CASE WHEN CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) > 20 THEN A.CD_ALUNO ELSE NULL END) AS '21 +',
COUNT(DISTINCT CASE WHEN CD_ETAPA_ENSINO IN (6,9,17) THEN A.CD_ALUNO ELSE NULL END) AS MATRICULAS
INTO ##MT_MEDIO_IDADE
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA 
WHERE CD_ETAPA_ENSINO IN (6,9,17)
GROUP BY B.DRE,B.SG_TP_ESCOLA, B.CD_ESCOLA,B.NOMESC
--SELECT * FROM ##MT_MEDIO_IDADE
--------------------------------------------------------------------------------------------------------------------------
--RECORTE - RACA
DROP TABLE ##MT_MEDIO_RACA
SELECT B.DRE,B.SG_TP_ESCOLA, B.CD_ESCOLA,B.NOMESC,--,A.SG_ETAPA,A.SG_SERIE_ENSINO,
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=1 THEN A.CD_ALUNO ELSE NULL END) AS 'BRANCA',
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=2 THEN A.CD_ALUNO ELSE NULL END) AS 'PRETA',
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=3 THEN A.CD_ALUNO ELSE NULL END) AS 'PARDA',
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=4 THEN A.CD_ALUNO ELSE NULL END) AS 'AMARELA',
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=5 THEN A.CD_ALUNO ELSE NULL END) AS 'INDIGENA',
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=6 THEN A.CD_ALUNO ELSE NULL END) AS 'NAO INFORMADA',
COUNT(DISTINCT CASE WHEN A.TP_RACA_COR=7 THEN A.CD_ALUNO ELSE NULL END) AS 'RECUSOU INFORMAR',
COUNT(DISTINCT CASE WHEN CD_ETAPA_ENSINO IN (6,9,17) THEN A.CD_ALUNO ELSE NULL END) AS MATRICULAS
INTO ##MT_MEDIO_RACA
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA 
WHERE CD_ETAPA_ENSINO IN (6,9,17)
GROUP BY B.DRE,B.SG_TP_ESCOLA, B.CD_ESCOLA,B.NOMESC
--SELECT * FROM ##MT_MEDIO_RACA
--------------------------------------------------------------------------------------------------------------------------
--RECORTE - SEXO
DROP TABLE ##MT_MEDIO_SEXO
SELECT B.DRE,B.SG_TP_ESCOLA, B.CD_ESCOLA,B.NOMESC,--,A.SG_ETAPA,A.SG_SERIE_ENSINO,
COUNT(DISTINCT CASE WHEN A.CD_SEXO_ALUNO = 'M' THEN A.CD_ALUNO ELSE NULL END) AS 'MASCULINO',
COUNT(DISTINCT CASE WHEN A.CD_SEXO_ALUNO = 'F' THEN A.CD_ALUNO ELSE NULL END) AS 'FEMININO',
COUNT(DISTINCT CASE WHEN CD_ETAPA_ENSINO IN (6,9,17) THEN A.CD_ALUNO ELSE NULL END) AS MATRICULAS
INTO ##MT_MEDIO_SEXO
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA 
WHERE CD_ETAPA_ENSINO IN (6,9,17)
GROUP BY B.DRE,B.SG_TP_ESCOLA, B.CD_ESCOLA,B.NOMESC
--SELECT * FROM ##MT_MEDIO_SEXO
--------------------------------------------------------------------------------------------------------------------------
--LISTA - ALUNOS ENS MEDIO
DROP TABLE ##LISTA_ALU_MEDI
SELECT distinct
B.DRE,
B.SG_TP_ESCOLA, 
B.CD_ESCOLA,
B.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.CD_ALUNO, 
CAST(DATEDIFF(DD, DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) AS IDADE,
C.dc_raca_cor,
A.cd_sexo_aluno
--INTO ##LISTA_ALU_MEDI
FROM SME_ALUNOS_DIARIO A
left JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA 
JOIN tipo_raca_cor  C ON A.TP_RACA_COR=C.tp_raca_cor
WHERE CD_ETAPA_ENSINO IN (6,9,17)
--SELECT * FROM ##LISTA_ALU_MEDI
--------------------------------------------------------------------------------------------------------------------------

--Quantidade de estudantes matriculados nos Itinerários Técnico/ Qualificação Profissional (Farmácia, Contabilidade, Marketing, Informática e Gerência em Saúde)
DROP TABLE ##ITINERARIOS_1
SELECT 
C.DRE,
C.SG_TP_ESCOLA,
C.CD_ESCOLA,
C.NOMESC,
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 5  THEN A.CD_MATRICULA ELSE NULL END) AS CONTABILIDADE,
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 7  THEN A.CD_MATRICULA ELSE NULL END) AS INFORMATICA,
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 9  THEN A.CD_MATRICULA ELSE NULL END) AS MARKETING,
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 26 THEN A.CD_MATRICULA ELSE NULL END) AS [FARMACIA],
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 19 THEN A.CD_MATRICULA ELSE NULL END) AS [FARMACIA NAO SME],
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 27 THEN A.CD_MATRICULA ELSE NULL END) AS [GERENCIA EM SAUDE],
COUNT(DISTINCT CASE WHEN A.cd_tipo_habilitacao_profissional = 21 THEN A.CD_MATRICULA ELSE NULL END) AS [GERENCIA EM SAUDE NAO SME]
INTO ##ITINERARIOS_1
FROM D_MATRICULA A
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA
WHERE C.TP_ESCOLA =3
GROUP BY
C.DRE,
C.SG_TP_ESCOLA,
C.CD_ESCOLA,
C.NOMESC
--SELECT * FROM ##ITINERARIOS_1
--------------------------------------------------------------------------------------------------------------------------------
--select cd_tipo_habilitacao_profissional,dc_tipo_habilitacao_profissional from tipo_habilitacao_profissional where cd_tipo_habilitacao_profissional in (5,7,9,19,20,21,26,27)
--------------------------------------------------------------------------------------------------------------------------------





