/*
Conforme e-mail TJSP_0048099, em anexo, deverão ser 
informados os nomes das crianças/adolescentes que 
foram matriculados nos anos de 2020, 2021 e 2022, 
nas escolas relacionadas no e-mail,  e que 
não possuem o nome do pai no registro de nascimento. 
Devem constar o nome da criança/adolescente, nome e endereço da mãe.
 */


	  select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Alceu Maynard%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Antonia Muotri Lamberga%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Antonio Figueiredo Amaral%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Armando de Arruda Pereira%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%CAsper LIbero%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Caxias%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Gabriel Prestes%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%HenriquE%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%JoAo MendonCa FalcAo%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%JoAo Theodoro%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Monteiro Lobato%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Nazir Miguel%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Patricia Galvao%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Santos Dumont%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Wilson Jose Abdalla%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Anita Costa%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Antonio Branco Lefevre%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Heitor Villa Lobos%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Ignacio Henrique RomeirO%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Indian%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%JoAo Carlos da Silva%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Maria Antonieta D%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Paulo Alves%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Tide Setubal%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%13 de Maio%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Alberto de Oliveira%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Ana Rosa de Araujo%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Angelo Martino%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Celso Leite Ribeiro Filho%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Icami Tiba%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Fabio da Silva Prado%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Faria Lima%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Jose de Moura%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Manoel de Paiva%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Marcilio Dias%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Neusa Bas%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Oswaldo Cruz%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Feijo%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Silvia Covas%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Tamandare%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Aluisio de AzevedO%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Analia Franco Bastos%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Cornelio Pires%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Eldy Rol%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Emiliano Di Cavalcanti%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Guilherme Rudge%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where nomesc like '%Mario Alves de Carvalho%'


---------------------------------------------------------------------------------------------------------------------------
	  select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Alceu Maynard%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Antonia Muotri Lamberga%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Antonio Figueiredo Amaral%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Armando de Arruda Pereira%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'CAsper LIbero%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Caxias%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Gabriel Prestes%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'HenriquE%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'JoAo MendonCa FalcAo%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'JoAo Theodoro%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Monteiro Lobato%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Nazir Miguel%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Patricia Galvao%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Santos Dumont%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Wilson Jose Abdalla%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Anita Costa%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Antonio Branco Lefevre%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Heitor Villa Lobos%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Ignacio Henrique RomeirO%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Indian%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'JoAo Carlos da Silva%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Maria Antonieta D%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Paulo Alves%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Tide Setubal%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like '13 de Maio%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Alberto de Oliveira%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Ana Rosa de Araujo%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Angelo Martino%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Celso Leite Ribeiro Filho%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Icami Tiba%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Fabio da Silva Prado%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Faria Lima%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Jose de Moura%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Manoel de Paiva%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Marcilio Dias%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Neusa Bas%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Oswaldo Cruz%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Feijo%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Silvia Covas%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Tamandare%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Aluisio de AzevedO%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Analia Franco Bastos%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Cornelio Pires%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Eldy Rol%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Emiliano Di Cavalcanti%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Guilherme Rudge%'
UNION select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC from SME_ESCOLA_DIARIO where cd_sit=1 and TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31)AND nomesc like 'Mario Alves de Carvalho%'


SELECT * FROM tipo_escola
