
--2023
SELECT
SG_ETAPA,
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())<=18) THEN CD_ALUNO ELSE NULL END) AS '<=18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())>18) THEN CD_ALUNO ELSE NULL END) AS'>18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL ) THEN CD_ALUNO ELSE NULL END) AS'>TOTAL'
FROM SME_ALUNOS_DIARIO 
WHERE DEF1 IS NOT NULL 
AND SG_ETAPA IS NOT NULL
GROUP BY SG_ETAPA WITH ROLLUP
--2022
SELECT
SG_ETAPA,
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())<=18) THEN CD_ALUNO ELSE NULL END) AS '<=18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())>18) THEN CD_ALUNO ELSE NULL END) AS'>18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL ) THEN CD_ALUNO ELSE NULL END) AS'>TOTAL'
FROM Db_Local_0_20220531.dbo.SME_ALUNOS 
WHERE DEF1 IS NOT NULL 
AND SG_ETAPA IS NOT NULL
GROUP BY SG_ETAPA WITH ROLLUP
--2021
SELECT
SG_ETAPA,
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())<=18) THEN CD_ALUNO ELSE NULL END) AS '<=18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())>18) THEN CD_ALUNO ELSE NULL END) AS'>18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL ) THEN CD_ALUNO ELSE NULL END) AS'>TOTAL'
FROM Db_Local_0_20210531.DBO.M_SME_ALUNOS_20210531 
WHERE DEF1 IS NOT NULL 
AND SG_ETAPA IS NOT NULL
GROUP BY SG_ETAPA WITH ROLLUP
/**********************************************************************************************************************************/
--2023
SELECT
CD_SEXO_ALUNO AS SEXO,
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())<=18) THEN CD_ALUNO ELSE NULL END) AS '<=18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())>18) THEN CD_ALUNO ELSE NULL END) AS'>18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL ) THEN CD_ALUNO ELSE NULL END) AS'>TOTAL'
FROM SME_ALUNOS_DIARIO 
WHERE DEF1 IS NOT NULL 
AND SG_ETAPA IS NOT NULL
GROUP BY CD_SEXO_ALUNO WITH ROLLUP
--2022
SELECT
CD_SEXO_ALUNO AS SEXO,
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())<=18) THEN CD_ALUNO ELSE NULL END) AS '<=18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())>18) THEN CD_ALUNO ELSE NULL END) AS'>18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL ) THEN CD_ALUNO ELSE NULL END) AS'>TOTAL'
FROM Db_Local_0_20220531.dbo.SME_ALUNOS 
WHERE DEF1 IS NOT NULL 
AND SG_ETAPA IS NOT NULL
GROUP BY CD_SEXO_ALUNO WITH ROLLUP
--2021
SELECT
CD_SEXO_ALUNO AS SEXO,
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())<=18) THEN CD_ALUNO ELSE NULL END) AS '<=18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL AND datediff (year,dt_nascimento_aluno,getdate())>18) THEN CD_ALUNO ELSE NULL END) AS'>18 ANOS',
COUNT(DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IS NOT NULL ) THEN CD_ALUNO ELSE NULL END) AS'>TOTAL'
FROM Db_Local_0_20210531.DBO.M_SME_ALUNOS_20210531 
WHERE DEF1 IS NOT NULL 
AND SG_ETAPA IS NOT NULL
GROUP BY CD_SEXO_ALUNO WITH ROLLUP
/**********************************************************************************************************************************/






