/*
Bom dia
Prezada Equipe DIE

Tendo em vista a orientação da COGED quanto à ampliação de atendimento de EMEI em período integral, 
solicitamos relatório dos 
1 - alunos matriculados em MGII 2023 que irão para Infantil em 2024 e cuja distância seja até 1,5km para as EMEIs e 
2 - alunos do Infantil 2023 que permanecerão na EMEI em 2024 abaixo relacionadas a fim de que possamos elaborar estudo de redução de turmas para 2024. 

Relatório de alunos do MGII 2023 para Infantil 2024  
Nome do aluno com matricula no MGII
EOL do aluno
Turma de matrícula
Endereço residencial
Distância para EMEI: 
EMEI VARGEM GRANDE - 11 salas - eol 019473
EMEI LUIZ GONZAGA - 8 salas - eol 019682
EMEI OSVALDO CORDEIRO - 6 salas - eol 098931
EMEI CLARA NUNES - 5 salas - eol 090646

2) Relatório de alunos de Infantil 2023 que permanecerão no Infantil em 2024
Nome do aluno com matricula no Infantil e que permanecerá no Infantil em 2024 
EOL do aluno
Permanência na EMEI: 
EMEI VARGEM GRANDE - 11 salas
EMEI LUIZ GONZAGA - 8 salas
EMEI OSVALDO CORDEIRO - 6 salas
EMEI CLARA NUNES - 5 salas
*/

SELECT 
A.DRE,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
NOME_ESCOLA,
ETAPA,
SERIE_ANO,
CD_TURMA_ESCOLA,
COD_ALUNO,
NOME_ALUNO,
CONCAT (TP_LOGRADOURO,' ',ENDEREÇO,', ',A.NR,'- ',A.COMPL,', ',A.BAIRRO) AS ENDEREÇO,
--VARGEM GRANDE I
CASE WHEN FLOOR(SQRT(POWER(((-46.704845*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.850532*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6 <=1500 THEN
FLOOR(FLOOR(SQRT(POWER(((-46.704845*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.850532*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6)
ELSE NULL END
AS 'VARGEM GRANDE I',
--LUIZ GONZAGA
CASE WHEN FLOOR(SQRT(POWER(((-46.720772*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.831025*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6 <=1500 THEN
FLOOR(FLOOR(SQRT(POWER(((-46.720772*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.831025*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6)
ELSE NULL END
AS 'LUIZ GONZAGA',
--CLARA NUNES
CASE WHEN FLOOR(SQRT(POWER(((-46.710892*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.683261*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6 <=1500 THEN
FLOOR(FLOOR(SQRT(POWER(((-46.710892*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.683261*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6)
ELSE NULL END
AS 'CLARA NUNES',
--OSVALDO CORDEIRO
CASE WHEN FLOOR(SQRT(POWER(((-46.671663*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.753491*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6 <=1500 THEN
FLOOR(FLOOR(SQRT(POWER(((-46.671663*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((-23.753491*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6)
ELSE NULL END
AS 'OSVALDO CORDEIRO',


A.CRDATE
INTO ##ALUNOS_MGII_CS
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS A
JOIN SME_ALUNOS_DIARIO B ON A.COD_ALUNO=B.CD_ALUNO
WHERE SERIE_ANO = 'MG II' AND A.DRE = 'DRE - CS'

/**********************************************************************************************************************************/
SELECT * into ##ALUNOS_MGII_CS1 FROM ##ALUNOS_MGII_CS WHERE [VARGEM GRANDE I] IS NOT NULL OR [LUIZ GONZAGA] IS NOT NULL OR [CLARA NUNES] IS NOT NULL OR [OSVALDO CORDEIRO] IS NOT NULL

--SELECT * FROM ##ALUNOS_MGII_CS1
/**********************************************************************************************************************************/

SELECT 
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.SG_ETAPA,
C.SG_SERIE_ENSINO,
A.CD_TURMA_ESCOLA,
A.CD_ALUNO,
A.NM_ALUNO,
--CONVERT(VARCHAR,A.DT_NASCIMENTO_ALUNO,103) AS DT_NASCIMENTO_ALUNO,
--CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) AS IDADE,
CONVERT(VArchar,A.CRDATE-1,103) AS DT_BASE
INTO ##ALUNOS_PERMANECEM_EMEI
FROM SME_ALUNOS_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA

INNER JOIN(SELECT	DISTINCT --EM TESE NÃO DEVERIA HAVER DUPLICADAS, MAS POR SEGURANÇA
        			CD_FAIXA,
        			CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA) + CONVERT(VARCHAR(2), MM_INICIO_FAIXA) + CONVERT(VARCHAR(2), DD_INICIO_FAIXA)) AS DT_INICIO_FAIXA,
        			CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_FIM_FAIXA) + CONVERT(VARCHAR(2), MM_FIM_FAIXA) + CONVERT(VARCHAR(2), DD_FIM_FAIXA)) AS DT_FIM_FAIXA,
        			CASE 
        				WHEN (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA)) = 1 THEN '0 E 1 ANO'
        				ELSE CONVERT(VARCHAR(2),(DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA))) + ' ANOS' 
        				END AS IDADE,
        			T1.CD_SERIE_ENSINO, 
        			T2.DC_SERIE_ENSINO,
        			T2.CD_CICLO_ENSINO,
        			T2.SG_SERIE_ENSINO,
        			T2.cd_etapa_ensino,
        			T3.dc_etapa_ensino
        	FROM	D_FAIXA_SERIE AS T1
        	INNER JOIN D_SERIE_ENSINO AS T2 ON T1.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
        	INNER JOIN D_ETAPA_ENSINO AS T3 ON T2.cd_etapa_ensino = T3.cd_etapa_ensino
        	WHERE	T1.DT_INICIO <= GETDATE()
        			AND (T1.DT_FIM IS NULL OR T1.DT_FIM >= CONVERT(DATE,GETDATE()))
        			AND TP_FAIXA =5) C  
					ON  A.DT_NASCIMENTO_ALUNO >= C.DT_INICIO_FAIXA
							AND A.DT_NASCIMENTO_ALUNO <= C.DT_FIM_FAIXA



WHERE C.CD_SERIE_ENSINO =23 AND A.CD_ESCOLA IN (019473,019682,098931,090646)

ORDER BY NOMESC


--SELECT * FROM SME_ALUNOS_DIARIO
--
--select * from VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS






