/*

SELECT 
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
C.dc_tipo_programa,
COUNT(DISTINCT CD_TURMA_ESCOLA) AS QT_TURMA,
SUM(AL_AT) AS MATR,
CONVERT(VARCHAR, A.CRDATE-1, 103) AS DT_BASE

FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE
A.CD_TIPO_PROGRAMA IN (426,603,103,104,105,301,302,303) AND A.DT_FIM IS  NULL
GROUP BY
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
C.dc_tipo_programa,
A.CRDATE

/********************************************************************************************************/
DROP TABLE ##REC_PAP
SELECT 
B.SG_TP_ESCOLA,
C.dc_tipo_programa,
COUNT(DISTINCT CD_TURMA_ESCOLA) AS QT_TURMA,
SUM(AL_AT) AS MATR,
CONVERT(VARCHAR, A.CRDATE-1, 103) AS DT_BASE
INTO ##REC_PAP
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE
A.CD_TIPO_PROGRAMA IN (426,603,103,104,105,302,303,553,554,555,569) AND A.DT_FIM IS  NULL
GROUP BY
B.SG_TP_ESCOLA,
C.dc_tipo_programa,
A.CRDATE
--select * from ##REC_PAP
*/
/**********************************************************************************************/

--13/06/2023
SELECT 
C.dc_tipo_programa,
COUNT(DISTINCT CD_TURMA_ESCOLA) AS QT_TURMA,
SUM(AL_AT) AS MATR,
CONVERT(VARCHAR, A.CRDATE-1, 103) AS DT_BASE
--INTO ##REC_PAP
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE
A.CD_TIPO_PROGRAMA IN (426,603,99,100,103,104,105,301,302,303,553,554,555,556,569)-- AND A.DT_FIM IS  NULL
GROUP BY
C.dc_tipo_programa,A.CRDATE

/**********************************************************************************************/

--31/05/2022
SELECT 
C.dc_tipo_programa,
COUNT(DISTINCT CD_TURMA_ESCOLA) AS QT_TURMA,
SUM(AL_AT) AS MATR,
CONVERT(VARCHAR, A.CRDATE-1, 103) AS DT_BASE
--INTO ##REC_PAP
FROM Db_Local_0_20220531.DBO.SME_CLASSES A
JOIN Db_Local_0_20220531.DBO.SME_ESCOLA B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE
A.CD_TIPO_PROGRAMA IN (426,603,99,100,103,104,105,301,302,303,553,554,555,556,569) --AND A.DT_FIM IS  NULL
GROUP BY
C.dc_tipo_programa,A.CRDATE


/**********************************************************************************************/

--31/05/2021
SELECT 
C.dc_tipo_programa,
COUNT(DISTINCT CD_TURMA_ESCOLA) AS QT_TURMA,
SUM(AL_AT) AS MATR,
CONVERT(VARCHAR, A.CRDATE-1, 103) AS DT_BASE
--INTO ##REC_PAP
FROM Db_Local_0_20210531.DBO.M_SME_CLASSES_20210531 A
JOIN Db_Local_0_20210531.DBO.M_SME_ESCOLA_20210531 B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE
A.CD_TIPO_PROGRAMA IN (426,603,99,100,103,104,105,301,302,303,553,554,555,556,569) --AND A.DT_FIM IS  NULL
GROUP BY
C.dc_tipo_programa,A.CRDATE



--SELECT * FROM D_TIPO_PROGRAMA WHERE DC_TIPO_PROGRAMA LIKE '%PAP%' OR DC_TIPO_PROGRAMA LIKE 'REC%' OR DC_TIPO_PROGRAMA LIKE '%AUTORAL%'




