
--CÓDIGO QUE CRIA SEQUENCIA NUMÉRICA DE OOOOOO ATÉ 888888(último código criado para testes de PRODAM)
WITH gerador (id) AS (
        SELECT 000001
        UNION ALL
        SELECT id + 1
		
        FROM gerador
        WHERE id <= 888888
       )
        SELECT id,
		CASE WHEN LEN(ID) < 6 THEN REPLICATE('0', 6 - LEN(ID)) + RTRIM(ID) ELSE CONVERT(NVARCHAR(6), ID) END AS COD  -- TRATA O CAMPO ID, ACRESCENTANDO ZEROS À ESQUERDA PARA MANTER TAMNHHO DO TEXTO COM 6 POSIÇÕES.
		INTO base_sequencia
		FROM gerador
        OPTION ( MAXRECURSION 0 )
      GO 
-----------------------------------------------------------
--CÓDIGO QUE COMPARA OS CÓDIGOS JÁ UTILIZADOS - VIEW
--DROP VIEW VW_COMPARA_CODIGOS 
CREATE VIEW VW_COMPARA_CODIGOS AS 
SELECT 
A.tp_escola,
dc_tipo_escola,sg_tp_escola,
cd_escola,
COD

FROM D_ESCOLA A
JOIN TIPO_ESCOLA B ON A.tp_escola=B.tp_escola
JOIN base_sequencia C ON A.cd_escola=C.COD collate SQL_Latin1_General_CP1_CI_AI
UNION
SELECT 
A.tp_unidade_administrativa,
dc_tipo_unidade_administrativa,sg_unidade_administrativa,
cd_unidade_administrativa,
COD

FROM D_UNIDADE_ADMINISTRATIVA A
JOIN TIPO_UNIDADE_ADMINISTRATIVA B ON A.tp_unidade_administrativa=B.tp_unidade_administrativa
JOIN base_sequencia C ON A.cd_unidade_administrativa=C.COD collate SQL_Latin1_General_CP1_CI_AI
---------------------------------------------------------------------------------------------------------------------------------------------------
--SELECT * FROM VW_COMPARA_CODIGOS

/**************************************************************************************************************************************************/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '00%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS                      /**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '01%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS						/**/
/**/  --SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '02%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS					/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '03%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS						/**/
/**/  --SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '04%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS					/**/
/**/  --SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '05%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS					/**/
/**/  --SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '06%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS					/**/
/**/  --SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '07%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS					/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '08%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS						/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '09%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --UNIDADES DIRETAS						/**/
																																				/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '1%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --OUTROS, FORA PMSP, ...					/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '2%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC  --CCAS, CEUS, ESCOLAS TECNICAS,CIEJA	/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '3%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC --CRECHES E ESOLAS PARTICULARES			/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '4%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC  --CRECHES INDIRETAS						/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '5%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC   --MOVA									/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '6%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC  --ESP CONVENIOS 						/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '7%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC  --CEU ATCOMPL							/**/
/**/  SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '8%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC 											/**/
/**/  --SELECT * FROM VW_COMPARA_CODIGOS WHERE COD LIKE '9%' AND CD_ESCOLA IS NOT NULL ORDER BY COD DESC 										/**/
/**************************************************************************************************************************************************/ 
