
--LISTA DE ESCOLAS DISTANTES ATE 1500 METROS DOS ENDEREÇOS DE ALUNOS DE ESCOLA ESPECÍFICA

DROP TABLE ##ESCOLAS_ELEGIVEIS
SELECT 
CD_ESCOLA,
CD_COORDENADA_GEO_Y AS LAT,
CD_COORDENADA_GEO_X AS LON,
SG_TP_ESCOLA,
NOMESC,
ENDERECO,
NR,
BAIRRO,
TP_ESCOLA
INTO ##ESCOLAS_ELEGIVEIS
FROM SME_ESCOLA_DIARIO
WHERE CD_SIT = 1 AND TP_ESCOLA IN (10,11,12,18,28,31)
--SELECT * FROM ##ESCOLAS_ELEGIVEIS
---------------------------------------------------------------------------------------------------------------


DROP TABLE ##ALUNOS_400636
SELECT 
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
NOME_ESCOLA,
ETAPA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,
--DIST_ALU_ESCOLA,
CONCAT(B.CD_ESCOLA,' ',B.SG_TP_ESCOLA,' ',B.NOMESC) AS ESC_DESTINO,
CONCAT (B.ENDERECO,', ',B.NR,' - ',B.BAIRRO) AS END_DESTINO,

FLOOR(FLOOR(SQRT(POWER(((LON_ALUNO*1000000) - (B.LON * 1000000) ),2) +  POWER(((LAT_ALUNO*1000000) - (B.LAT * 1000000)),2)) / 10)/0.6) AS DIST_DESTINO

INTO ##ALUNOS_400636
FROM TBL_ENDERECOS_ALUNOS A, ##ESCOLAS_ELEGIVEIS B

WHERE A.CD_ESCOLA=400636
AND FLOOR(FLOOR(SQRT(POWER(((LON_ALUNO*1000000) - (B.LON * 1000000) ),2) +  POWER(((LAT_ALUNO*1000000) - (B.LAT * 1000000)),2)) / 10)/0.6)<=1500