
/*Por favor, solicitamos o encaminhamento do arquivo dos endereços das crianças de 
MGII dos distritos da Consolação, República, Santa Cecília e Sé, com distância até 1,5 KM das EMEIs.
*/

DROP TABLE ##EMEIS
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
DISTR,
CD_COORDENADA_GEO_Y AS LAT_ESCOLA,
CD_COORDENADA_GEO_X AS LON_ESCOLA

INTO ##EMEIS

FROM SME_ESCOLA_DIARIO WHERE TP_ESCOLA IN(2,17,28,31) AND CD_SIT=1
--SELECT * FROM ##EMEIS
----------------------------------------------------------------------------------
DROP TABLE ##ALUNOS_MGII
select
A.DRE,
B.DISTR AS DISTRITO,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
NOME_ESCOLA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,

CONCAT (ENDEREÇO,', ',A.NR,' ',A.COMPL,' - ',A.BAIRRO) AS ENDERECO_ALUNO,
LAT_ALUNO,
LON_ALUNO
INTO ##ALUNOS_MGII
from TBL_ENDERECOS_ALUNOS A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE B.CD_DIST IN (26,66,69,78) AND SERIE_ANO='MG II'
--SELECT * FROM ##ALUNOS_MGII
--------------------------------------------------------------------
DROP TABLE ##EMEIS_ATE_1500M_ALUNOS_MGII
SELECT 
A.DRE,
A.DISTRITO,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
NOME_ESCOLA,
SERIE_ANO,
COD_ALUNO,
NOME_ALUNO,
ENDERECO_ALUNO,
CONCAT(B.DRE,'- ',B.CD_ESCOLA,'- ',B.SG_TP_ESCOLA,'',B.NOMESC) AS EMEI_DESTINO,
--B.DRE,
--B.CD_ESCOLA,
--B.SG_TP_ESCOLA,
--B.NOMESC,
FLOOR(FLOOR(SQRT(POWER(((B.LON_ESCOLA*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((B.LAT_ESCOLA*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6) AS [DIST_ALU_EMEI(m)]
INTO ##EMEIS_ATE_1500M_ALUNOS_MGII
FROM ##ALUNOS_MGII A,  ##EMEIS B 
WHERE FLOOR(FLOOR(SQRT(POWER(((B.LON_ESCOLA*1000000) - (A.LON_ALUNO * 1000000) ),2) +  POWER(((B.LAT_ESCOLA*1000000)  - (A.LAT_ALUNO * 1000000)),2)) / 10)/0.6)<=1500
--SELECT * FROM ##EMEIS_ATE_1500M_ALUNOS_MGII