

SELECT DISTINCT
A.*,
B.MATR 
INTO ##CL_LIMPEZA
FROM [dbo].[LISTA_ESCOLAS_LIMPEZA] A

LEFT JOIN (SELECT 
		   CD_ESCOLA,SG_TP_ESCOLA, 
		   (CASE WHEN SG_TP_ESCOLA = 'CEU AT COMPL' THEN MT_ATIV_COMP 
		   ELSE
		   ISNULL(MT_EI,0)+ISNULL(MT_FUND,0)+ISNULL(MT_MEDI,0)+ISNULL(MT_EJA,0) END )AS MATR
           FROM D_MISME_ESCOLA_TOTAL)  B ON A.[Código EOL]= B.CD_ESCOLA COLLATE Latin1_General_CI_AS
WHERE DRE ='Campo Limpo'


