
/*Solicitamos, por gentileza, para estudo de demanda uma planilha com nome do aluno, filiação, contatos, endereço completo das seguintes unidades escolares:
    
     CEI MARIA FERREIRA DA FONSECA - 309767
     CEI ALEGRIA DO APRENDER 308408
     CEI NINHO DA AMIZADE 308556
     CEI PAIS E FILHOS 308542
     CEI PAPA JOÃO XXIII 400413

      Há a possibilidade de enviar também uma planilha de cadastro específicos para 
	  CEI Salvador Lo Turco 400224
	  e CEI Pequenos do Butantã II 308882
	  com nome do aluno, contatos, endereço completo.
*/
DROP TABLE ##LISTA_ALUNOS_ESCOLAS_ESPECIFICAS
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOME_ESCOLA, 
ETAPA,
SERIE_ANO,
NOME_ALUNO,
MÃE_ALUNO,
RESPONSÁVEL,
TEL_CELULAR,
TEL_FIXO,
CONCAT(TP_LOGRADOURO, ' ',ENDEREÇO,', ',NR,' ',COMPL,' - ',BAIRRO) AS END_ALUNO
INTO ##LISTA_ALUNOS_ESCOLAS_ESPECIFICAS FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS WHERE CD_ESCOLA IN (309767,308408,308556,308542,400413) ORDER BY CD_ESCOLA
--SELECT * FROM ##LISTA_ALUNOS_ESCOLAS_ESPECIFICAS


DROP TABLE ##CADASTRO_ESCOLA_ESPECIFICA_400224_308882
SELECT 
CD_ALUNO,
NM_ALUNO,
NM_MAE,
DC_ETAPA_ENSINO,
[DESC. SÉR. ENS.],
DT_INSCRICAO,
AGUARDANDO,
TP_PREFERENCIA,
CD_UNIDADE_EDUCACAO,
B.SG_TP_ESCOLA,
NOMESC,
LOGRADOURO_ALU,
NR_ALU,
COMP_ALU,BAIRRO_ALU 
INTO ##CADASTRO_ESCOLA_ESPECIFICA_400224_308882
FROM ALUNOS_CADASTRO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_UNIDADE_EDUCACAO=B.CD_ESCOLA
 WHERE TP_PREFERENCIA='E' AND CD_UNIDADE_EDUCACAO IN (400224,308882)
 --SELECT * FROM ##CADASTRO_ESCOLA_ESPECIFICA_400224_308882