

/*
LISTA DE ALUNOS 1500 M ATE ESCOLA ESPECÍFICA

Por gentileza, solicitamos uma planilha com os alunos matriculados que residam até 1,5 km 
da Avenida Antônio Ramiro da Silva, s/n (Distrito /setor Rio Pequeno 6702).
A planilha precisa conter 
nome do aluno, 
filiação, 
data de nascimento,  
endereço completo, 
agrupamento ao qual esta matriculado,
km do seu endereço até o CEI Dom Claudio Hummes (Avenida Antônio Ramiro da Silva, s/n).

*/
DROP TABLE ##DESTINO
SELECT CONCAT(SG_TP_ESCOLA,NOMESC) AS DESTINO,CD_COORDENADA_GEO_Y, CD_COORDENADA_GEO_X
INTO ##DESTINO
FROM SME_ESCOLA_DIARIO WHERE CD_ESCOLA = 400887
--SELECT * FROM ##DESTINO

DROP TABLE ##ALUNOS_ATE1500M
SELECT 
A.DRE,A.CD_ESCOLA,A.SG_TP_ESCOLA,NOME_ESCOLA,COD_ALUNO,NOME_ALUNO,MÃE_ALUNO,RESPONSÁVEL,
CONCAT(TP_LOGRADOURO,ENDEREÇO,',',NR,COMPL,BAIRRO) AS END_ALUNO,

ETAPA,SERIE_ANO,DESTINO, 


FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  
				 POWER((LON_ALUNO * 1000000 - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6) AS DISTANCIA


INTO ##ALUNOS_ATE1500M
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS A, ##DESTINO B

WHERE FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  
				 POWER((LON_ALUNO * 1000000 - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6<=1500 AND SERIE_ANO IN ('BERC I','BERC II','MG I','MG II','MG UNIF')

DROP TABLE ##ALUNOS_ATE1500M_1
SELECT A.DRE,A.CD_ESCOLA,A.SG_TP_ESCOLA,NOME_ESCOLA,COD_ALUNO,NOME_ALUNO,MÃE_ALUNO,RESPONSÁVEL,END_ALUNO,ETAPA,SERIE_ANO,DT_NASCIMENTO_ALUNO, DESTINO,DISTANCIA
INTO ##ALUNOS_ATE1500M_1
FROM ##ALUNOS_ATE1500M A
JOIN SME_ALUNOS_DIARIO B ON A.COD_ALUNO=B.CD_ALUNO
--SELECT * FROM ##ALUNOS_ATE1500M_1 ORDER BY 2