--VAGAS E MATRÍCULAS UNIDADES ESP CONV



DROP TABLE ##MATR_ESP_CONV
SELECT
DRE,
B.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
C.dc_tipo_programa AS MODALIDADE,
SUM(QT_VAGA_OFERECIDA) AS VAGAS,
SUM (AL_AT) AS MATR,
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE


INTO ##MATR_ESP_CONV
 from SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA 
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE TP_ESCOLA=26
GROUP BY
DRE,
B.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
C.dc_tipo_programa,
A.CRDATE
--SELECT * FROM ##MATR_ESP_CONV ORDER BY 1


