
--MATRICULAS CCA

DROP TABLE ##MATRICULAS_CCA
SELECT DISTINCT
DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
COUNT(CASE WHEN TP_ESCOLA=29 THEN CD_ALUNO ELSE NULL END) AS MATR_CCA
INTO ##MATRICULAS_CCA
 FROM SME_ALUNOS_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE TP_ESCOLA=29
GROUP BY
DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC
--SELECT * FROM ##MATRICULAS_CCA

