
USE Db_Local_0
DROP TABLE ##MATR_AT_COMPL_CEU
SELECT DISTINCT
DRE,
SG_TP_ESCOLA,
CD_ESCOLA,
NOMESC,
TURNO,
CL_ATIV_COMP,
MT_ATIV_COMP
INTO ##MATR_AT_COMPL_CEU
FROM MISME_ESCOLA_MTN WHERE SG_TP_ESCOLA ='CEU AT COMPL'

--SELECT * FROM ##MATR_AT_COMPL_CEU


