--Resumo - matriculas ENS MÉDIO

DROP TABLE ##MATR_ENS_MEDIO
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
MT_MEDI,
MT_M1,
MT_M2,
MT_M3,
MT_M4
INTO ##MATR_ENS_MEDIO
FROM Db_Set_22..MISME_ESCOLA_TOTAL WHERE MT_MEDI>0
UNION
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
MT_MEDI,
MT_M1,
MT_M2,
MT_M3,
MT_M4
FROM Db_Set_22..MISME_EE_ESCOLA_TOTAL WHERE MT_MEDI>0
--ORDER BY SG_TP_ESCOLA WITH ROLLUP

SELECT * FROM ##MATR_ENS_MEDIO
