/* Escolas Ensino funadamental com até 14 classes/turmas*/

DROP TABLE ##EMEFS_COM_ATE_14_TURMAS
SELECT 
DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,
CL_F1 AS [QT TURMAS 1º ANO],
CL_F2 AS [QT TURMAS 2º ANO],
CL_F3 AS [QT TURMAS 3º ANO],
CL_F4 AS [QT TURMAS 4º ANO],
CL_F5 AS [QT TURMAS 5º ANO],
CL_F6 AS [QT TURMAS 6º ANO],
CL_F7 AS [QT TURMAS 7º ANO],
CL_F8 AS [QT TURMAS 8º ANO],
CL_F9 AS [QT TURMAS 9º ANO],
CL_FUND AS [QT CLASSES],
CRDATE
INTO ##EMEFS_COM_ATE_20_TURMAS
FROM MISME_ESCOLA_TOTAL
WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND CL_FUND<=20
--SELECT * FROM ##EMEFS_COM_ATE_20_TURMAS


