USE Db_Local_0

--QUANTIDADE DE CEMEI
DROP TABLE ##QT_CEMEI
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
ENDERECO,
NR,
CEP,
BAIRRO,
DC_SUB_PREFEITURA,
CONVERT(VARCHAR, CRDATE-1,103) AS DT_BASE
INTO ##QT_CEMEI
FROM SME_ESCOLA_DIARIO 
WHERE TP_ESCOLA IN (28,31)
AND CD_SIT=1
--SELECT * FROM ##QT_CEMEI
----------------------------------------------------

