USE Db_Local_0
--QUADRO RESUMO - QTDE DE ESCOLAS ATIVAS


DROP TABLE ##QTDE_ESCOLAS_ATIVAS
SELECT
DRE,
COUNT (DISTINCT CASE WHEN TP_ESCOLA IN (10,18) THEN CD_ESCOLA ELSE NULL END) AS 'CEI DIR',
COUNT (DISTINCT CASE WHEN TP_ESCOLA IN (2,17) THEN CD_ESCOLA ELSE NULL END) AS 'EMEI',
COUNT (DISTINCT CASE WHEN TP_ESCOLA IN (1,16) THEN CD_ESCOLA ELSE NULL END) AS 'EMEF',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =3 THEN CD_ESCOLA ELSE NULL END) AS 'EMEFM',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =4 THEN CD_ESCOLA ELSE NULL END) AS 'EMEBS',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =13 THEN CD_ESCOLA ELSE NULL END) AS 'CIEJA',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =23 THEN CD_ESCOLA ELSE NULL END) AS 'CMCT',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =30 THEN CD_ESCOLA ELSE NULL END) AS 'CECI',
COUNT (DISTINCT CASE WHEN TP_ESCOLA IN (28,31)THEN CD_ESCOLA ELSE NULL END) AS 'CEMEI',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =27 THEN CD_ESCOLA ELSE NULL END) AS 'CEU',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =11THEN CD_ESCOLA ELSE NULL END) AS 'CEI INDIR',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =12 THEN CD_ESCOLA ELSE NULL END) AS 'CRECHE CONV',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =22 THEN CD_ESCOLA ELSE NULL END) AS 'MOVA',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =14 THEN CD_ESCOLA ELSE NULL END) AS 'CCI/CIPS',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =15 THEN CD_ESCOLA ELSE NULL END) AS 'ESCOLAS PARTICULARES',
COUNT (DISTINCT CASE WHEN TP_ESCOLA =26 THEN CD_ESCOLA ELSE NULL END) AS 'ESP CONVENIADO',
COUNT (DISTINCT CASE WHEN TP_ESCOLA IN (10,18,2,17,1,16,3,4,13,23,30,28,31,27,11,12,22,14,15,26) THEN CD_ESCOLA ELSE NULL END) AS 'TOTAL'
INTO ##QTDE_ESCOLAS_ATIVAS
FROM SME_ESCOLA_DIARIO
WHERE CD_SIT=1
GROUP BY DRE with rollup
--SELECT * FROM ##QTDE_ESCOLAS_ATIVAS
----------------------------------------------------------------------------------------------------------------------------------------


