
USE Db_Local_0

--exec BI_ESCOLA_AMBIENTE


DROP TABLE ##LISTA_ESCOLAS_QUANTITATIVOS_FUNCIONARIOS_DRE_LIMPEZA
SELECT
A.DRE,
A.TIPO,
A.[NOME UNIDADE EDUCACIONAL],
A.TURNOS,
A.[Funcionários Fixos],
A.[QTD ATUAL FUNC],
A.Campo7 AS OBS,
A.CD_ESCOLA,
   (ISNULL([SALA DE AULA PROPRIA],0)+
	ISNULL([SALA DE AULA ADAPTADA],0)+
	ISNULL([SALA DE ED. INFANTIL PROPRIA],0)+
	ISNULL([SALA DE ED. INFANTIL ADAPTADA],0)+
	ISNULL([SALA DE ED. ESPECIAL PROPRIA],0)+
	ISNULL([SALA DE ED. ESPECIAL ADAPTADA],0)+
	ISNULL([SALA DE EDUCACAO ARTISTICA],0)+
	ISNULL(BERCARIO,0)) AS QT_SALAS_AULA,
	
	(ISNULL(MT_EI,0)+
	ISNULL(MT_FUND,0)+
	ISNULL(MT_MEDI,0)+
	ISNULL(MT_EJA,0)) AS MATRICULAS
INTO ##LISTA_ESCOLAS_QUANTITATIVOS_FUNCIONARIOS_DRE_LIMPEZA
FROM LISTA_LIMPEZA A
LEFT JOIN ##ESCOLA_AMBIENTES_LINEAR B ON A.CD_ESCOLA=B.CD_ESCOLA COLLATE Latin1_General_CI_AS
LEFT JOIN MISME_ESCOLA_TOTAL C ON A.CD_ESCOLA=C.CD_ESCOLA COLLATE Latin1_General_CI_AS
GROUP BY
A.DRE,
A.TIPO,
A.[NOME UNIDADE EDUCACIONAL],
A.TURNOS,
A.[Funcionários Fixos],
A.[QTD ATUAL FUNC],
A.Campo7,
A.CD_ESCOLA,
[SALA DE AULA PROPRIA],
[SALA DE AULA ADAPTADA],
[SALA DE ED. INFANTIL PROPRIA],
[SALA DE ED. INFANTIL ADAPTADA],
[SALA DE ED. ESPECIAL PROPRIA],
[SALA DE ED. ESPECIAL ADAPTADA],
[SALA DE EDUCACAO ARTISTICA],
BERCARIO,
MT_EI,
MT_FUND,
MT_MEDI,
MT_EJA
--SELECT * FROM ##LISTA_ESCOLAS_QUANTITATIVOS_FUNCIONARIOS_DRE_LIMPEZA
-------------------------------------------------------------------------------------------