--RELAÇÃO DE UNIDADES COM QUANTIDADE DE ALUNOS NEE

DROP TABLE ##DEF1_IN_EDINF
SELECT 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
COUNT (DISTINCT CASE WHEN (DEF1 IS NOT NULL AND SG_ETAPA IN ('ED INF','ED INF ESP') AND B.TP_ESCOLA  NOT IN (14,15,32,33,34,35,36,37)) THEN CD_ALUNO ELSE NULL END) AS MATR,
convert(varchar,A.CRDATE-1, 103) AS DT_BASE
INTO ##DEF1_IN_EDINF
FROM Db_Fev_23..SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE DEF1 IS NOT NULL AND SG_ETAPA IN ('ED INF','ED INF ESP') AND B.TP_ESCOLA  NOT IN (14,15,32,33,34,35,36,37)
GROUP BY 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
A.CRDATE
--SELECT * FROM ##DEF1_IN_EDINF

select * from D_TIPO_ESCOLA


select * from NEE_SEE


