
/*
Relação de DREs e orgãos internos das DREs

select * from [AJ30MMAA-COMPL]
*/

DROP TABLE ##DRE_SETORES
SELECT 
--DIRET_MUN AS DRE,
CODLOC,
TIPO,
DESLOC,
ENDERECO,
NUMERO,
BAIRRO,
A.DISTRITO
--A.Cod_Tipo_proprietario

INTO ##DRE_SETORES

FROM [AJ30MMAA-COMPL] A
JOIN [dbo].[DREMDIST] B ON A.DISTRITO=B.DISTRITO
--LEFT JOIN tipo_proprietario C ON A.Cod_Tipo_proprietario=C.tp_proprietario
WHERE TPLOC=24 AND CODIGO_STATUS=1

UNION

SELECT 
--DIRET_MUN AS DRE,
CODLOC,
TIPO,
DESLOC,
ENDERECO,
NUMERO,
BAIRRO,
A.DISTRITO
--A.Cod_Tipo_proprietario
FROM [AJ30MMAA-COMPL] A
JOIN [dbo].[DREMDIST] B ON A.DISTRITO=B.DISTRITO
WHERE TPLOC =8 AND CODIGO_STATUS=1 AND DESLOC LIKE  '%DRE%' 

UNION

SELECT 
--DIRET_MUN AS DRE,
CODLOC,
TIPO,
DESLOC,
ENDERECO,
NUMERO,
BAIRRO,
A.DISTRITO
--A.Cod_Tipo_proprietario


FROM [AJ30MMAA-COMPL] A
JOIN [dbo].[DREMDIST] B ON A.DISTRITO=B.DISTRITO
WHERE TPLOC =9 AND CODIGO_STATUS=1 AND DESLOC LIKE  '%NAE%' 

--SELECT * FROM ##DRE_SETORES



SELECT * FROM tipo_proprietario
