USE Db_Local_0
--(1,16,3,2,17,4,30,10,18,28,11,12,13,22,23,14,25)
----------------------------------------------------------------------------------------------
--RESUMO DE ESCOLAS ATIVAS
DROP TABLE ##RESUMO_ESCOLAS

SELECT	DRE,
		[EMEF] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (1,16) THEN CD_ESCOLA END)),
		[EMEFM] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (3) THEN CD_ESCOLA END)),
		[EMEI] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (2,17) THEN CD_ESCOLA END)),
		[EMEBS] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (4) THEN CD_ESCOLA END)),
		[CECI] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (30) THEN CD_ESCOLA END)),
		[CEI DIRET] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (10,18) THEN CD_ESCOLA END)),
		[CEMEI] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (28,31) THEN CD_ESCOLA END)),
		[CEI INDIR] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (11) THEN CD_ESCOLA END)),
		[CR.P.CONV] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (12) THEN CD_ESCOLA END)),
		[CIEJA] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (13) THEN CD_ESCOLA END)),
		[MOVA] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (22) THEN CD_ESCOLA END)),
		[CMCT] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (23) THEN CD_ESCOLA END)),
		[CCI/CIPS] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (14) THEN CD_ESCOLA END)),
		[E TECNICA] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (25) THEN CD_ESCOLA END)),
		[TOTAL] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (1,16,3,2,17,4,30,10,18,28,11,12,13,22,23,14,25,31) THEN CD_ESCOLA END)),
		[ESC PART]= COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (15) THEN CD_ESCOLA END))
INTO ##RESUMO_ESCOLAS
FROM SME_ESCOLA_DIARIO
WHERE CD_SIT = 1		
GROUP BY DRE
UNION
SELECT	'TOTAL'  AS DRE,
		[EMEF] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (1,16) THEN CD_ESCOLA END)),
		[EMEFM] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (3) THEN CD_ESCOLA END)),
		[EMEI] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (2,17) THEN CD_ESCOLA END)),
		[EMEBS] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (4) THEN CD_ESCOLA END)),
		[CECI] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (30) THEN CD_ESCOLA END)),
		[CEI DIRET] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (10,18) THEN CD_ESCOLA END)),
		[CEMEI] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (28,31) THEN CD_ESCOLA END)),
		[CEI INDIR] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (11) THEN CD_ESCOLA END)),
		[CR.P.CONV] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (12) THEN CD_ESCOLA END)),
		[CIEJA] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (13) THEN CD_ESCOLA END)),
		[MOVA] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (22) THEN CD_ESCOLA END)),
		[CMCT] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (23) THEN CD_ESCOLA END)),
		[CCI/CIPS] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (14) THEN CD_ESCOLA END)),
		[E TECNICA] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (25) THEN CD_ESCOLA END)),
		[TOTAL] = COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (1,16,3,2,17,4,30,10,18,28,11,12,13,22,23,14,25,31) THEN CD_ESCOLA END)),
		[ESC PART]= COUNT(DISTINCT (CASE WHEN TP_ESCOLA IN (15) THEN CD_ESCOLA END))
FROM SME_ESCOLA_DIARIO
WHERE CD_SIT = 1		
--SELECT * FROM ##RESUMO_ESCOLAS

-----------------------------------------------------------------------------------------
--select * from tipo_escola