
--LISTA DE ESCOLAS DA REDE DIRETA COM SALAS DE RECURSOS MULTIFUNCIONAIS

DROP TABLE ##SALAS_SRM
SELECT 
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
B.dc_tipo_ambiente,
COUNT (DISTINCT A.CD_AMBIENTE_ESCOLA) AS QTDE
INTO ##SALAS_SRM
FROM D_AMBIENTE_ESCOLA A
JOIN D_TIPO_AMBIENTE B ON A.tp_ambiente=B.tp_ambiente
JOIN SME_ESCOLA_DIARIO C ON A.cd_escola=C.CD_ESCOLA

WHERE A.tp_ambiente=10000 AND A.dt_fim IS NULL AND C.TP_ESCOLA IN (1,2,3,4,10,13,14,16,17,18,23,25,28,31)
GROUP BY
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
B.dc_tipo_ambiente
--SELECT * FROM ##SALAS_SRM

--SELECT * FROM D_TIPO_AMBIENTE WHERE dc_tipo_ambiente LIKE '%SALA%'